let mapleader="\<Space>"

let g:syntastic_python_checkers = ['pyflakes', 'pep8', 'flake8', 'pylint']
let g:syntastic_always_populate_loc_list = 1

" airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
" have airline at start
set laststatus=2

" for vim-gitgutter
highlight clear SignColumn
highlight GitGutterAdd ctermfg=green guifg=darkgreen
highlight GitGutterChange ctermfg=yellow guifg=darkyellow
highlight GitGutterDelete ctermfg=red guifg=darkred
highlight GitGutterChangeDelete ctermfg=yellow guifg=darkyellow

runtime! config/**/*.vim
