#!/bin/bash
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
xcompmgr -n &
stalonetray \
    --icon-gravity E \
    --geometry 4x1-0+0 \
    --max-geometry 4x1-0+0 \
    --background '#002b36' \
    --skip-taskbar \
    --icon-size 24 \
    --kludges force_icons_size \
    --window-strut none \
    &
gnome-settings-daemon &
sleep 2
gnome-screensaver &
export $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
gnome-power-manager &
xkbcomp -I$HOME/.xkb ~/.xkb/keymap/jamesw :0
redshift &
exec xmonad
