#!/bin/bash
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
xcompmgr -c &
stalonetray \
    --icon-gravity E \
    --geometry 5x1-0+0 \
    --max-geometry 5x1-0+0 \
    --background '#0f111a' \
    --skip-taskbar \
    --icon-size 24 \
    --kludges force_icons_size \
    --window-strut none \
    --window-layer bottom \
    &
gnome-settings-daemon &
sleep 2
gnome-screensaver &
export $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
gnome-power-manager &
xkbcomp -I$HOME/.xkb ~/.xkb/keymap/jamesw :0
redshift &
feh --no-fehbg --bg-fill ~/devel/dotfiles/xmonad/background.jpg
exec xmonad
